Nav bar
nburd90/crispy-couscous pull request #13
Opened 2021-02-24 22:52 UTC by nburd90

Basic navbar with some boostrap styles.

2021-02-24 23:13 UTC, billythakidd04 requested changes
Before I get too far into this. The bootstrap css should be pulled in via cdn not local. This will ensure you don't have to maintain the css if something changes.

2021-02-25 14:27 UTC, nburd90 commented
Ah yeah that’s true. I’ll make sure I change that up.

On Wed, Feb 24, 2021 at 18:14 Bill <notifications@github.com> wrote:

> *@billythakidd04* requested changes on this pull request.
>
> Before I get too far into this. The bootstrap css should be pulled in via
> cdn not local. This will ensure you don't have to maintain the css if
> something changes.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/nburd90/crispy-couscous/pull/13#pullrequestreview-598020795>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASXNK7E7QYM5FFATADPOEALTAWB4BANCNFSM4YFMVSLQ>
> .
>

2021-02-25 19:33 UTC, tfrazzini13 submitted a review, later dismissed

2021-02-25 20:10 UTC, billythakidd04 commented
There are still conflicts so I'm waiting on those to get fixed.

2021-02-25 20:41 UTC, nburd90 commented
Commit # - c408c78e46a36efbc780bf5a53174bf2c31709fc 

Conflicts should be fixed.

2021-02-25 21:44 UTC, WaymonBrown84 approved these changes

2021-02-25 21:50 UTC, tfrazzini13 approved these changes

2021-02-25 22:11 UTC, billythakidd04 requested changes
1. delete the bootstrap css file, use cdn
2. format your files
3. adjust the navbar so its not a generic copy paste

2021-02-25 22:11 UTC, billythakidd04 commented on nav-bar.php
> +<body>
you dont need any of this if you're just including it on other pages

2021-02-25 22:11 UTC, billythakidd04 commented on nav-bar.php
> +</html>
remove all this its not needed

2021-02-25 22:29 UTC, billythakidd04 approved these changes

2021-02-25 22:31 UTC, merged

2021-02-25 22:38 UTC, tfrazzini13 reviewed
got it all good