News html
nburd90/crispy-couscous pull request #29
Opened 2021-03-10 01:55 UTC by nburd90

- Created div structure for html. 
- Will edit positioning and layout in #22.
- Will added further html if needed.

2021-03-10 02:13 UTC, billythakidd04 requested changes
Kill the extraneous commented code if its not getting used.

2021-03-10 02:13 UTC, billythakidd04 commented on news.php
> +                <div class="news-image-holder" style="background:url(crispy-images/newspic2.jpeg)"></div>-->
Remove the commented code if its not getting used

2021-03-10 02:13 UTC, billythakidd04 commented on news.php
> +                <div class="news-image-holder" style="background: url(crispy-images/newspic3.jpg);"></div>-->
deleted commented code

2021-03-10 15:56 UTC, billythakidd04 requested changes

2021-03-10 15:56 UTC, billythakidd04 commented on news.php
> +                <div class="newsItem">
fix your whitespace formatting here

2021-03-10 15:56 UTC, billythakidd04 commented on news.php
> +                <div class="newsItem">
formatting

2021-03-11 01:44 UTC, nburd90 commented on news.php
> +                <div class="newsItem">
8b3bf4c

2021-03-11 01:44 UTC, nburd90 commented on news.php
> +                <div class="newsItem">
8b3bf4c

2021-03-11 16:26 UTC, billythakidd04 requested changes
if this is giving you trouble text me. formatting is extremely important for readability. on the job, you won't be the last person to touch your code. its important to leave it so _others_ can read it easily.

2021-03-11 16:26 UTC, billythakidd04 commented on news.php
>                      <p class="header-medium">2021</p>
ok now the p tag is off... did you run an auto format?

2021-03-11 22:39 UTC, billythakidd04 approved these changes

2021-03-12 16:08 UTC, merged